class_name GDProject
## GENERATED by `gd palette` / `gd playtest` from the effective config
## (gsd-gd/config.json overridden by .planning/config.json). Do not edit.
##
## These are THIS project's numbers. Read them instead of hardcoding a
## budget in game code - a literal here is a number that disagrees with
## the gate.

const BUDGET := {
	"max_asset_tris": {"character": 12000, "environment_module": 3000, "hero_prop": 6000, "prop": 1500},
	"max_draw_calls": 450,
	"max_shadow_casting_lights": 1,
	"max_tris_per_frame": 900000,
	"min_fps": 60,
}

static func budget(key: String, fallback: Variant = 0) -> Variant:
	return BUDGET.get(key, fallback)
