class_name Palette
## GENERATED by `gd palette` from .planning/COLOR_BIBLE.md. Do not edit.
##
## Use Palette.get_color("key") / Palette.material("key") instead of typing a
## hex anywhere in game code. If a colour you need is not here, the answer is
## a new row in the Color Bible with a reason - not a literal in a script.

const COLORS := {
	"base_dark": Color("12161f"),
	"base_mid": Color("2a3342"),
	"base_light": Color("55637a"),
	"accent_warm": Color("e08a3c"),
	"accent_cool": Color("4f7fa8"),
	"metal_raw": Color("6e7479"),
	"metal_worn": Color("4a4d50"),
	"organic_dark": Color("1d2a1e"),
	"organic_light": Color("4a6b41"),
	"emissive_signal": Color("ff4436"),
	"emissive_guide": Color("7fe3d0"),
}

const SURFACE := {
	"base_dark": {"roughness": 0.85, "metallic": 0.0, "emission": 0.0},
	"base_mid": {"roughness": 0.8, "metallic": 0.0, "emission": 0.0},
	"base_light": {"roughness": 0.72, "metallic": 0.0, "emission": 0.0},
	"accent_warm": {"roughness": 0.55, "metallic": 0.0, "emission": 0.0},
	"accent_cool": {"roughness": 0.6, "metallic": 0.0, "emission": 0.0},
	"metal_raw": {"roughness": 0.38, "metallic": 0.9, "emission": 0.0},
	"metal_worn": {"roughness": 0.62, "metallic": 0.8, "emission": 0.0},
	"organic_dark": {"roughness": 0.88, "metallic": 0.0, "emission": 0.0},
	"organic_light": {"roughness": 0.8, "metallic": 0.0, "emission": 0.0},
	"emissive_signal": {"roughness": 0.4, "metallic": 0.0, "emission": 2.5},
	"emissive_guide": {"roughness": 0.4, "metallic": 0.0, "emission": 1.8},
}

static func get_color(key: String) -> Color:
	assert(COLORS.has(key), "'%s' is not in the Color Bible" % key)
	return COLORS.get(key, Color.MAGENTA)  # magenta = you shipped an unpalettable colour


static func material(key: String) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.albedo_color = get_color(key)
	var s: Dictionary = SURFACE.get(key, {})
	m.roughness = s.get("roughness", 0.7)
	m.metallic = s.get("metallic", 0.0)
	if float(s.get("emission", 0.0)) > 0.0:
		m.emission_enabled = true
		m.emission = get_color(key)
		m.emission_energy_multiplier = s["emission"]
	return m
